# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ceb54ea14df2d56605b3ec42aa3128244440d630f372b7b4ca3657f6952eab3e45d322028e988d8792a1ed2cd29ba746a47f067a32c1ad6371d6b38ba7675f2a

test:
  secret_key_base: c595cc35f620a71e0d09af7215a840633ed726a9821eead094537a3d820a5a2fe4a3bed8ed81f28361b1490d2a67a5892a529dd2d22a43d45c587e643576f389

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
#  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: 347366050f75f4f6fe655f995a05bdcfc574ee58d08968fdf61306829ffebd49b03ae8ed85f70b4e1544ba0db7c86d8c1778d459b69b21f92f1282e35290f183
